src/resources/dictionary.json, src/test/repetition.test.ts
=> Evaluate-expression can be multiline

src/time/timeParser.ts
=> Force upper case for date template string

src/config.ts, src/keywordHandler.ts, src/regExpressions.ts, src/test/expr.test.ts, src/test/script.test.ts, src/test/sql.test.ts, src/validator.ts
=> Check blocks for nesting

src/resources/dictionary.json, src/test/type.test.ts
=> Allow `source = message-stat`

src/regExpressions.ts, src/resources/dictionary.json, src/test/undefinedVar.test.ts, src/validator.ts
Fixed undefined CSV variable bug: https://apps.axibase.com/chartlab/948896a7/11
=> CSV variable is undefined

package.json, src/resources/dictionary.json
* `disconnect-interval` and `disconnect-count` are now supported at `[series]` level
=> Update dictionary settings

src/formatter.ts, src/jsFormatter.ts, src/test/scriptFormatting.test.ts
Closes #20 
Now Formatter doesn't delete comments.
=> Preserve comments

src/resources/dictionary.json
=> Allow 'path' at [widget] level

src/jsFormatter.ts, src/test/scriptFormatting.test.ts
=> Invalid JavaScript formatting

src/resources/dictionary.json, src/test/columnSections.test.ts
=> Duplicate columns are allowed

src/test/columnSections.test.ts, src/validator.ts
=> Fix: [column] interpreted as [tags]

src/test/freemarker.test.ts, src/validator.ts
=> Replace links

src/formatter.ts, src/test/indents.test.ts
=> Fix '=' sign indents

src/formatter.ts, src/regExpressions.ts, src/test/var.test.ts, src/validator.ts
=> Multiline var bracket next line support

src/formatter.ts, src/regExpressions.ts, src/test/comentsFormating.test.ts
=> Improve comments formatting

src/test/alias.test.ts, src/validator.ts
Closes #23 
Fixed conflict of dealiases and settings with the same name. Now error message is shown in the right place ⤵️
Also rewrote dealiases tests.
=> Improve dealiases handling

src/setting.ts, src/test/type.test.ts, src/validator.ts
=> Validate each item of `multiple` setting list

src/test/alias.test.ts, src/validator.ts
Closes #72 
Got rid of this error ⤵️
Title is not a script setting, so check doesn't need to be performed.
=> No aliases check for non-script settings

src/formatter.ts, src/jsFormatter.ts, src/nestedCodeFormatter.ts, src/regExpressions.ts, src/test/comentsFormating.test.ts, src/test/expr.test.ts, src/test/formatBlankLines.test.ts, src/test/indents.test.ts, src/test/scriptFormatting.test.ts, src/test/sql.test.ts, src/test/var.test.ts
Transferred PR from axibase/axibase-charts-vscode#363
=> Inline script formatting

src/resources/dictionary.json
Allow multiline declaration of `rule`
=> Allow multiple `rule`

src/resources/descriptions.md, src/resources/dictionary.json
Added `on-title-click` to dictionary. Waiting for axibase/charts#175 to be merged.
=> Add `on-title-click` setting

src/setting.ts, src/test/size.test.ts
=> Fix 'size' set as 'alias' false error

src/resources/dictionary.json
=> Some corrections in dictionary.json

src/regExpressions.ts, src/test/templateVar.test.ts, src/util.ts, src/validator.ts
Now variables (declared via `var` keyword) are supported in `@{}` templates.
=> Add templates variables support

src/resources/dictionary.json
=> Changed section in downsample settings

src/resources/descriptions.md, src/setting.ts, src/time/index.ts
=> Removed unnecessary caching

src/relatedSettingsRules/presenceValidation/noUselessSettings/forWidget.ts, src/test/dateFilter.test.ts, src/test/multiple.test.ts, src/test/scope.test.ts, src/test/test.ts, src/test/type.test.ts, src/validator.ts
=> Fixed validation and refactored tests

src/configTree/section.ts, src/messageUtil.ts, src/relatedSettingsRules/index.ts, src/relatedSettingsRules/presenceValidation/alwaysRequiredForSeries.ts, src/resourcesProviderBase.ts, src/test/alwaysRequiredForSeries.test.ts, src/test/required.test.ts, src/validator.ts
=> Entity in `change-field`

src/completionProvider.ts, src/languageService.ts, src/relatedSettingsRules/presenceValidation/requiredForSeriesAlways.ts, src/resources/descriptions.md, src/resources/dictionary.json, src/resourcesProviderBase.ts, src/test/completionProvider.test.ts, src/test/helpers/resourcesProvider.ts, src/test/scope.test.ts, src/test/type.test.ts
* Add examples to settings definition
* Update validation of entity field to support instrument/symbol/class
* Add support of external value competions for instrument completion. The completion itself will be implemented in charts-editor
=> Financial entity validation and completions

src/resources/descriptions.md, src/resources/dictionary.json
Add `hide-interval`, `hide-gap`, and `ohlcv` statistic
=> Add new financial settings
